name: .NET Core

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-rc.1.20452.10
    - name: Install dependencies
      run: dotnet restore DotRealDb.OnlySrc.sln
    - name: Build
      run: dotnet build DotRealDb.OnlySrc.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test DotRealDb.OnlySrc.sln --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack DotRealDb.OnlySrc.sln --configuration Release --no-restore -o .packages/
    - name: Push
      run: dotnet nuget push packages/*.nupkg --source ${{secrets.NUGET_SOURCE}} --api-key ${{secrets.NUGET_KEY}}  --skip-duplicate
      continue-on-error: true
